version: '3.7'
services:
  urlhaus:
    image: urlhaus-searcher:0.0.1-SNAPSHOT
    restart: always
    environment:
      - spring_profiles_active=live
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  postgres:
    image: postgis/postgis:13-master
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'